ig_credentials:
  - username: foo 
    password: bar 

max_followed_scraped: 999
follows_page_size: 50
sleep:
  between_account_batches:
    minimum: 16
    maximum: 32
  between_accounts:
    minimum: 0.85 
    maximum: 4
accounts_per_batch:
  minimum: 16
  maximum: 32
  
rate_limit_retries: 5
exponential_sleep_base: 3
exponential_sleep_offset: 15
